import{useMemo,useState,useEffect}from'react';import{ShieldCheck,FlaskConical,MessageSquare,Settings,Activity,Play,RotateCcw,Copy,CheckCircle2,XCircle}from'lucide-react';import{processPayload,uuid,detectTypes,getConfig,putConfig}from'./lib/api';import type{AuditRow}from'./types';
const templates=[['Паспорт','Иванов Иван Иванович, паспорт 4509 123456'],['Карта + CVV','Карта 4276 3800 1234 5678, CVV 321'],['ФИО + телефон','Петров Пётр Сергеевич, +7 (999) 123-45-67'],['Адрес','Адрес: г. Москва, ул. Тверская, д. 10, кв. 5']];
function Masked({text}:{text:string}){const p=text.split(/(\*+)/g);return <pre className="output">{p.map((x,i)=>x.includes('*')?<mark key={i}>{x}</mark>:x)}</pre>}
function App(){const[tab,setTab]=useState('sandbox');const[id,setId]=useState('');const[payload,setPayload]=useState(templates[0][1]);const[masked,setMasked]=useState('');const[restored,setRestored]=useState('');const[raw,setRaw]=useState('');const[tele,setTele]=useState<{latency?:number,status?:number,tokens?:number}>({});const[err,setErr]=useState('');const[audit,setAudit]=useState<AuditRow[]>([]);const[retry,setRetry]=useState(0);
 const add=(op:any,pid:string,lat:number,status:number,text:string,ra?:string)=>setAudit(x=>[{time:new Date().toLocaleTimeString('ru-RU'),payloadId:pid,operation:op,latency:lat,status,types:detectTypes(text),tokens:Math.ceil(text.length/4),retryAfter:ra},...x].slice(0,100));
 async function call(op:'Маскирование'|'Демаскирование',text:string,pid:string){setErr('');try{const r=await processPayload(text,pid);setRaw(JSON.stringify({result:r.result},null,2));setTele({latency:r.latency,status:r.status,tokens:Math.ceil(text.length/4)});add(op,pid,r.latency,r.status,text,r.retryAfter);return r.result}catch(e:any){setTele({latency:e.latency,status:e.status,tokens:Math.ceil(text.length/4)});add(op,pid,e.latency||0,e.status||0,text,e.retryAfter);if(e.status===429){const n=parseInt(e.retryAfter||'1')||1;setRetry(n);let v=n;const t=setInterval(()=>{v--;setRetry(v);if(v<=0)clearInterval(t)},1000)}setErr(e.status===400?'Ошибка 400: проверьте payload и payload_id.':e.status===500?'Ошибка 500: внутренняя ошибка сервера.':e.status===429?`429 Too Many Requests. Повтор через ${e.retryAfter||'?'} сек.`:e.message);return null}}
 async function mask(){const pid=uuid();setId(pid);setRestored('');const r=await call('Маскирование',payload,pid);if(r!==null)setMasked(r)}async function unmask(){if(!id||!masked)return;const r=await call('Демаскирование',masked,id);if(r!==null)setRestored(r)}async function full(){const pid=uuid();setId(pid);setRestored('');const m=await call('Маскирование',payload,pid);if(m===null)return;setMasked(m);const r=await call('Демаскирование',m,pid);if(r!==null)setRestored(r)}
 const nav=[['sandbox','Песочница',FlaskConical],['chat','LLM-цепочка',MessageSquare],['config','Конфигуратор',Settings],['audit','Аудит и метрики',Activity]] as const;
 return <div className="app"><aside><div className="brand"><ShieldCheck/> <div><b>PD Security</b><small>Control Center</small></div></div><nav>{nav.map(([k,n,I])=><button className={tab===k?'active':''} onClick={()=>setTab(k)}><I size={18}/>{n}</button>)}</nav><div className="server"><span/> Backend: localhost:8080</div></aside><main><header><div><h1>Модуль безопасности ПД</h1><p>Локальный стенд тестирования контракта и демонстрации</p></div><span className="env">LOCAL ENV</span></header>{tab==='sandbox'&&<section><div className="title"><div><h2>Direct API Inspector</h2><p>Проверка полного цикла POST /process</p></div><button className="primary" onClick={full} disabled={retry>0}><Play size={17}/> Полный цикл</button></div>{err&&<div className="alert">{err}{retry>0&&` · ${retry} сек.`}</div>}<div className="grid2"><div className="card"><label>payload_id</label><div className="row"><input value={id} onChange={e=>setId(e.target.value)} placeholder="Будет создан при маскировании"/><button onClick={()=>setId(uuid())}>UUID v4</button><button onClick={()=>setId('')}>Очистить</button></div><label>payload</label><textarea value={payload} onChange={e=>setPayload(e.target.value)} rows={9}/><div className="chips">{templates.map(t=><button onClick={()=>setPayload(t[1])}>{t[0]}</button>)}</div><div className="actions"><button className="primary" onClick={mask}>1. Выполнить маскирование</button><button onClick={unmask} disabled={!masked}>2. Выполнить демаскирование</button></div></div><div className="card"><div className="metrics"><div><span>LATENCY</span><b>{tele.latency??'—'} ms</b></div><div><span>STATUS</span><b className={tele.status===200?'ok':'bad'}>{tele.status??'—'}</b></div><div><span>≈ TOKENS</span><b>{tele.tokens??'—'}</b></div></div><label>Замаскированный результат</label>{masked?<Masked text={masked}/>:<div className="empty">Результат шага 1 появится здесь</div>}<label>Сырой JSON</label><pre className="json">{raw||'{\n  "result": "..."\n}'}</pre>{restored&&<div className={restored===payload?'success':'failure'}>{restored===payload?<CheckCircle2/>:<XCircle/>}<div><b>{restored===payload?'SUCCESS':'DIFF ERROR'}</b><p>{restored===payload?'Демаскированный текст посимвольно совпадает с оригиналом.':'Результат отличается от исходного текста.'}</p></div></div>}</div></div></section>}{tab==='chat'&&<Chat call={call}/>} {tab==='config'&&<Config/>}{tab==='audit'&&<Audit rows={audit}/>}</main></div>}
function Chat({call}:{call:any}){const[input,setInput]=useState('Составь выписку по клиенту Иванов Иван Иванович, паспорт 4509 123456');const[m,setM]=useState('');const[llm,setL]=useState('');const[fin,setF]=useState('');async function run(){const id=uuid();const x=await call('Маскирование',input,id);if(!x)return;setM(x);const answer=`Выписка сформирована для: ${x}`;setL(answer);const y=await call('Демаскирование',answer,id);if(y)setF(y)}return <section><div className="title"><div><h2>End-to-End Chat</h2><p>Клиент → Маскирование → LLM → Демаскирование</p></div><button className="primary" onClick={run}><Play size={17}/> Запустить цепочку</button></div><div className="card"><label>Промпт пользователя</label><textarea rows={4} value={input} onChange={e=>setInput(e.target.value)}/></div><div className="pipeline"><div className="card"><b>1 · Исходный запрос</b><pre>{input}</pre></div><div className="card safe"><b>2 · Data-in-Transit</b><p className="hint">Во внешний контур передается только маска</p><Masked text={m||'Ожидание запуска...'}/></div><div className="card"><b>3 · Ответ + демаскирование</b><small>Ответ модели</small><pre>{llm||'—'}</pre><small>Финальный ответ</small><pre>{fin||'—'}</pre></div></div></section>}
const TYPE_LABELS:Record<string,string>={FIO:'ФИО',PHONE:'Телефон',EMAIL:'Email',PASSPORT:'Паспорт РФ',PASS_CODE:'Код подразделения',PASS_AUTHORITY:'Кем выдан',DATE:'Дата',DRIVER:'Вод. удостоверение',INN:'ИНН',CARD:'Номер карты',CARD_EXP:'Срок карты',CVV:'CVV / CVC',PIN:'ПИН-код',CARD_HOLDER:'Держатель карты',ADDRESS:'Адрес',BIRTHPLACE:'Место рождения',CITIZENSHIP:'Гражданство',PASSPORT_INTL:'Загранпаспорт',SNILS:'СНИЛС'};
const ALL_TYPES=Object.keys(TYPE_LABELS);
function Config(){
 const[cfg,setCfg]=useState<any>(null);const[sel,setSel]=useState('');const[saved,setSaved]=useState(false);const[err,setErr]=useState('');
 useEffect(()=>{getConfig().then(c=>{setCfg(c);const ids=Object.keys(c.systems||{});setSel(ids[0]||'')}).catch(()=>setErr('Не удалось загрузить конфигурацию с бэкенда'))},[]);
 if(err)return <section><div className="alert">{err}</div></section>;
 if(!cfg)return <section><div className="empty">Загрузка конфигурации…</div></section>;
 const systems=cfg.systems||{};
 const sys=systems[sel]||{enabled:true,mask_types:[],demask_enabled:true,strategy:'token'};
 const checked=new Set<string>((sys.mask_types&&sys.mask_types.length)?sys.mask_types:ALL_TYPES);
 const updateSys=(patch:any)=>{setCfg({...cfg,systems:{...systems,[sel]:{...sys,...patch}}});setSaved(false)};
 const setGlobal=(patch:any)=>{setCfg({...cfg,...patch});setSaved(false)};
 const toggleType=(t:string)=>{const s=new Set(checked);s.has(t)?s.delete(t):s.add(t);updateSys({mask_types:[...s]})};
 const addSystem=()=>{const id=(prompt('ID новой системы (заголовок X-System-ID):')||'').trim();if(!id)return;setCfg({...cfg,systems:{...systems,[id]:{enabled:true,mask_types:[],demask_enabled:true,strategy:'token'}}});setSel(id);setSaved(false)};
 const save=async()=>{setErr('');try{const ok=await putConfig({auth_enabled:!!cfg.auth_enabled,composite_masking:!!cfg.composite_masking,systems});ok?setSaved(true):setErr('Ошибка сохранения')}catch{setErr('Ошибка сохранения')}};
 return <section>
  <div className="title"><div><h2>Конфигуратор систем и правил</h2><p>Управление политиками потребителей — сохраняется на бэкенде</p></div><button className="primary" onClick={save}><Play size={16}/> Сохранить</button></div>
  {saved&&<div className="success"><CheckCircle2/><div><b>Сохранено</b><p>Правила применены на бэкенде и действуют для /process.</p></div></div>}
  {err&&<div className="alert">{err}</div>}
  <div className="instruction"><b>Инструкция по настройке</b><p>Включите контроль доступа, чтобы правила систем начали действовать (иначе маскируется всё). Выберите или добавьте систему-потребителя и задайте её ID (передаётся в заголовке X-System-ID). Отметьте типы ПД для маскирования, разрешите демаскирование при необходимости и выберите стратегию маски. Нажмите «Сохранить» — правила применятся на бэкенде немедленно. Проверьте политику в песочнице (запрос с нужным X-System-ID).</p></div>
  <div className="grid2">
   <div className="card">
    <Toggle label="Контроль доступа (auth_enabled)" value={!!cfg.auth_enabled} set={(v:boolean)=>setGlobal({auth_enabled:v})}/>
    <Toggle label="Составное маскирование (карта+пин)" value={!!cfg.composite_masking} set={(v:boolean)=>setGlobal({composite_masking:v})}/>
    <hr/>
    <label>Система-потребитель (X-System-ID)</label>
    <div className="row"><select value={sel} onChange={e=>setSel(e.target.value)}>{Object.keys(systems).map(id=><option key={id} value={id}>{id}</option>)}</select><button onClick={addSystem}>+ Добавить</button></div>
    <Toggle label="Разрешить обращения системы" value={!!sys.enabled} set={(v:boolean)=>updateSys({enabled:v})}/>
    <Toggle label="Разрешить демаскирование" value={!!sys.demask_enabled} set={(v:boolean)=>updateSys({demask_enabled:v})}/>
    <label>Стратегия маскирования</label>
    <select value={sys.strategy||'token'} onChange={e=>updateSys({strategy:e.target.value})}><option value="token">token — [FIO_1]</option><option value="asterisks">asterisks — ****</option><option value="synthetic">synthetic — фейки</option></select>
   </div>
   <div className="card"><h3>Матрица типов ПД (маскировать)</h3><div className="checks">{ALL_TYPES.map(t=><label key={t}><input type="checkbox" checked={checked.has(t)} onChange={()=>toggleType(t)}/><span>{TYPE_LABELS[t]}</span></label>)}</div></div>
  </div>
 </section>;
}
function Toggle({label,value,set}:{label:string,value:boolean,set:any}){return <div className="toggleRow"><span>{label}</span><button className={'toggle '+(value?'yes':'')} onClick={()=>set(!value)}><i/></button></div>}
function Audit({rows}:{rows:AuditRow[]}){const avg=rows.length?Math.round(rows.reduce((a,b)=>a+b.latency,0)/rows.length):0;const r429=rows.filter(x=>x.status===429);const tok=rows.reduce((a,b)=>a+b.tokens,0);const seconds=Math.max(1,rows.length?rows.reduce((a,b)=>a+b.latency,0)/1000:1);return <section><div className="title"><div><h2>Аудит и метрики</h2><p>Телеметрия текущей сессии — чувствительные значения не сохраняются</p></div></div><div className="stats"><div><span>Средний latency</span><b>{avg} ms</b></div><div><span>429 Too Many Requests</span><b>{r429.length}</b><small>{r429[0]?.retryAfter?`Retry-After: ${r429[0].retryAfter}`:'Retry-After: —'}</small></div><div><span>Обработано токенов</span><b>{tok}</b><small>≈ {(tok/seconds).toFixed(1)} TPS</small></div><div><span>Запросов в сессии</span><b>{rows.length}</b></div></div><div className="card tablewrap"><table><thead><tr><th>Время</th><th>payload_id</th><th>Операция</th><th>Latency</th><th>Статус</th><th>Выявленные типы ПД</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.time}</td><td className="mono">{r.payloadId.slice(0,8)}…</td><td>{r.operation}</td><td>{r.latency} ms</td><td><span className={'status s'+r.status}>{r.status||'NET'}</span></td><td>{r.types.length?r.types.map(x=><em>{x}</em>):'—'}</td></tr>)}{!rows.length&&<tr><td colSpan={6} className="emptycell">История появится после первого запроса к /process</td></tr>}</tbody></table></div></section>}
export default App;
